development:
  adapter: postgresql
  encoding: unicode
  database: groupfundr_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: groupfundr_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: groupfundr_production
  pool: 5

cucumber:
  <<: *test